# Site configuration
baseURL = 'https://example.org/'
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
title = 'cviper blog'
copyright = "© [Utku](https://github.com/cviper13). All content is original unless stated otherwise."
theme = 'risotto'
sectionPagesMenu = "main"

# Pagination
[pagination]
pagerSize = 3

# Basic parameters
[params]
noindex = false

# Theme configuration
[params.theme]
#palette = "base16-black-metal-venom" # or "dark-funeral"
palette = "base16-grayscale-dark" # light version "base16-grayscale-light" is also available

# About section
[params.about]
title = "cviper13"
description = "A digital den for projects, notes, experiments, and rants from a high school dev obsessed with planes, scooters, and systems that break in interesting ways."
logo = "🐧"
#logo-image = "static/apple-touch-icon.png" # Uncomment to use a logo image

# Social links
[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/cviper13"

# Menu configuration
[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

# Taxonomy configuration
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# Markup configuration
[markup]
[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = true

# Privacy settings
[privacy]
[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

# Services configuration
[services]
[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
